apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 156348148676.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 156348148676.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 219d33c0
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
